      - name: Install dependencies
        run: |
          TARGET_DIR=$(find . -maxdepth 3 -name "package.json" -path "*/client/package.json" -print -quit)
          TARGET_DIR=$(dirname "$TARGET_DIR")
          echo "Moving to $TARGET_DIR"
          cd "$TARGET_DIR"
          npm install

      - name: Run Puppeteer tests
        run: |
          TARGET_DIR=$(find . -maxdepth 3 -name "package.json" -path "*/client/package.json" -print -quit)
          TARGET_DIR=$(dirname "$TARGET_DIR")
          cd "$TARGET_DIR"
          npm test