name: CI-Tests
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and Test
        run: |
          # נכנסים ישירות לתיקייה, בלי חיפושים
          cd client || cd webPro-main/client || cd webPro-main/webPro-main/client
          npm install
          npm test